name: Auto Major Version Bump

on:
  push:
    branches:
      - main

jobs:
  bump-major:
    if: contains(github.event.head_commit.message, '#major')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to read tags

      - name: Configure git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Get latest version tag
        id: get_tag
        run: |
          echo "tag=$(git describe --tags --abbrev=0 2>/dev/null || echo v0.0.0)" >> $GITHUB_OUTPUT

      - name: Calculate next major version
        id: next
        run: |
          latest="${{ steps.get_tag.outputs.tag }}"
          version="${latest#v}"
          IFS='.' read -r major minor patch <<< "$version"
          major=$((major+1))
          next="v${major}.0.0"
          echo "new_tag=$next" >> $GITHUB_OUTPUT

      - name: Create and push new major tag
        run: |
          git tag ${{ steps.next.outputs.new_tag }}
          git push origin ${{ steps.next.outputs.new_tag }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.next.outputs.new_tag }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
